### PR TITLE
Add XJM Docker image

### PR DESCRIPTION
**Pull request by mkordas**
It is a mirror of XHT image with `indent` added.

@yegor256 after review please merge, publish to Docker Hub and set up automated build, thanks!

### CODE REVIEW

**Comment by mkordas** [comment]
@yegor256 I need your help here

**Comment by mkordas** [comment]
@yegor256 ping

**Comment by mkordas** [comment]
@yegor256 ping again

**Comment by yegor256** [comment]
@mkordas here it is: https://hub.docker.com/r/yegor256/xjm/

**Comment by yegor256** [comment]
@mkordas should be built after 6da099a

**Comment by mkordas** [comment]
@yegor256 thanks a lot, build is successful: https://hub.docker.com/r/yegor256/xjm/builds/banmnjmthmyvba2vnge9hch/

**Pull request merged**
