### PR TITLE
XB Docker image added

### PR DESCRIPTION
**Pull request by original-brownbear**
@yegor256 need this one :)

### CODE REVIEW

**Comment by original-brownbear** [comment]
@yegor256 ping :)

**Comment by yegor256** [comment]
@original-brownbear done: https://hub.docker.com/r/yegor256/xb/

**Comment by yegor256** [comment]
@original-brownbear would be great if you explain it in README

**Comment by original-brownbear** [comment]
@yegor256 #6 :)

**Comment by yegor256** [comment]
@original-brownbear right, thanks. Docker hub will build an image now

**Pull request merged**
