### PR TITLE
XHT Docker Image

### PR DESCRIPTION
**Pull request by original-brownbear**
XHT Docker Image

### CODE REVIEW

**Comment by yegor256** [comment]
@original-brownbear thanks

**Comment by yegor256** [comment]
@original-brownbear it's here: https://hub.docker.com/r/yegor256/xht/

**Comment by original-brownbear** [comment]
@yegor256 thanks, can you also trigger the build please ?
It does not run the first build one automatically :)

**Comment by yegor256** [comment]
@original-brownbear done: https://hub.docker.com/r/yegor256/xht/builds/

**Pull request merged**
