### PR TITLE
added lsof to xht image

### PR DESCRIPTION
**Pull request by caarlos0**
refs https://github.com/teamed/xockets-hadoop-transport/issues/2051

### CODE REVIEW

**Comment by original-brownbear** [comment]
@yegor256 can you merge this one?, it's the right solution.

**Comment by caarlos0** [comment]
@yegor256 ping

**Comment by caarlos0** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@caarlos0 @original-brownbear done

**Comment by original-brownbear** [comment]
@yegor256 thanks! :)

**Comment by caarlos0** [comment]
@yegor256 thanks =D

**Pull request merged**
